<a href="https://colab.research.google.com/github/gyuholee94/NLP/blob/master/06%EB%8B%A8%EC%96%B4%ED%91%9C%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
word_ls = ['원숭이', '바나나', '사과', '사과']

In [79]:
from collections import defaultdict

In [13]:
defaultdict?

디폴트딕은 딕셔너리 만들때 키값만 넣고 벨류 안넣어도 되는, 벨류가 디폴트로 정해둔 값으로 되는 함수야

In [80]:
import numpy as np

In [81]:
def one_hot_encode(word_ls):
  word2id_dic = defaultdict(lambda:len(word2id_dic))

  for word in word_ls:
    word2id_dic[word]
  
  n_unique_words = len(word2id_dic)
  one_hot_vectors = np.zeros((len(word_ls), n_unique_words))

  for i, word in enumerate(word_ls):
    index = word2id_dic[word]
    one_hot_vectors[i, index] = 1
  return one_hot_vectors


In [82]:
one_hot_vectors = one_hot_encode(word_ls)
one_hot_vectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [83]:
word_ls = ['원숭이', '바나나', '사과', '코끼리']
one_hot_vectors = one_hot_encode(word_ls)
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [85]:
values =array(word_ls)
print(values)
print('-'*15)
label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)
print(int_enc)#0으로 된 제로스에서 인덱스를 표현
print('-'*15)
onehot_enc = OneHotEncoder(sparse=False)
int_enc = int_enc.reshape(len(int_enc), 1) #n:1 matrix로 변환
print(int_enc)#데이터 아낄 수 있음
onehot_enc = onehot_enc.fit_transform(int_enc)
print(onehot_enc)
print('-'*15)
onehot_enc = OneHotEncoder(sparse=True)
int_enc = int_enc.reshape(len(int_enc), 1) #n:1 matrix로 변환
print(int_enc)
onehot_enc = onehot_enc.fit_transform(int_enc)
print(onehot_enc)

['원숭이' '바나나' '사과' '코끼리']
---------------
[2 0 1 3]
---------------
[[2]
 [0]
 [1]
 [3]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
---------------
[[2]
 [0]
 [1]
 [3]]
  (0, 2)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 3)	1.0


In [86]:
inverted = label_enc.inverse_transform([argmax(onehot_enc[0, :])])
print(inverted)

['원숭이']


In [87]:
onehot_enc[0, :]

<1x4 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [88]:
argmax(onehot_enc[0, :])

2

In [89]:
label_enc.inverse_transform([argmax(onehot_enc[0, :])])

array(['원숭이'], dtype='<U3')

#밀집벡터

In [90]:
word_embedding_dic = {
    '사과': [1.0, 0.5],
    '바나나' : [0.9, 1.2],
    '원숭이' : [0.5, 1.5]
}

In [91]:
import numpy as np
def euclidean_dist(x,y):
  x = np.array(x)
  y = np.array(y)
  return np.sqrt(np.sum(x-y)**2)

In [92]:
euclidean_dist(word_embedding_dic['사과'], word_embedding_dic['바나나'])

0.6

In [93]:
def cosine_similarity(x, y):
  nominator = np.dot(x, y)
  denominator = np.linalg.norm(x)*np.linalg.norm(y)
  return nominator/denominator

In [94]:
a = np.array([1, 2])
b = np.array([3, 4])
np.dot(a, b)

11

In [95]:
a = np.array(word_embedding_dic['사과'])
b = np.array(word_embedding_dic['바나나'])
np.dot(a, b)

1.5

In [96]:
a = np.array([1, 2])
np.linalg.norm(a)

2.23606797749979

In [97]:
print(cosine_similarity(word_embedding_dic['사과'], word_embedding_dic['바나나']))
print(euclidean_dist(word_embedding_dic['사과'], word_embedding_dic['바나나']))

0.8944271909999159
0.6


In [98]:
print(cosine_similarity(word_embedding_dic['사과'], word_embedding_dic['원숭이']))
print(euclidean_dist(word_embedding_dic['사과'], word_embedding_dic['원숭이']))

0.7071067811865475
0.5


In [99]:
print(cosine_similarity(word_embedding_dic['바나나'], word_embedding_dic['원숭이']))
print(euclidean_dist(word_embedding_dic['바나나'], word_embedding_dic['원숭이']))

0.9486832980505138
0.09999999999999998


In [100]:
s1 = '대부분 원숭이는 바나나를 좋아합니다.'
s2 = '코주부 원숭이는 바나나를 싫어합니다.'

In [101]:
# 토큰화를 수행합니다.
token_s1 = s1.split()
token_s2 = s2.split()


In [102]:
union = set(token_s1).union(set(token_s2))
print(union)

{'원숭이는', '대부분', '바나나를', '싫어합니다.', '코주부', '좋아합니다.'}


In [103]:
intersection = set(token_s1).intersection(set(token_s2))
print(intersection)


{'원숭이는', '바나나를'}


In [104]:
print(len(intersection)/len(union)) # 2를 6로 나눔.


0.3333333333333333


#3 TF-IDF를 활용한 단어 벡터


In [51]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"


In [52]:
from math import log10


In [53]:
# document 내 토큰이 등장한 빈도수 계산
def f(t, d):
    return d.count(t)


In [54]:
# tf 계산
def tf(t, d):
    return 0.5 + 0.5*f(t,d)/max([f(w,d) for w in d])


In [55]:
# idf 계산
def idf(t, D):
    numerator = len(D)
    denominator = 1 + len([ True for d in D if t in d])
    return log10(numerator/denominator) + 1

In [56]:
# tf-idf 계산
def tfidf(t, d, D):
    #print(D)
    print(t)
    #print(d)
    print(tf(t,d))
    print(idf(t, D))
    print(tf(t,d)*idf(t, D))
    print("===")
    return tf(t,d)*idf(t, D)

In [57]:
# 공백을 기준으로 토큰과
def tokenizer(d):
    return d.split()


In [58]:
# tfidf 계산 
def tfidfScorer(D):
    tokenized_D = [tokenizer(d) for d in D]
    result = []
    for d in tokenized_D:
        result.append([(t, tfidf(t, d, tokenized_D)) for t in d])
    return result

In [60]:
corpus = [d1, d2]
for i, doc in enumerate(tfidfScorer(corpus)):
    print('====== document[%d] ======' % i)
    print(doc)

The
0.75
0.8239087409443188
0.6179315557082391
===
cat
1.0
1.0
1.0
===
sat
0.75
0.8239087409443188
0.6179315557082391
===
on
0.75
0.8239087409443188
0.6179315557082391
===
my
0.75
0.8239087409443188
0.6179315557082391
===
face
0.75
1.0
0.75
===
I
0.75
0.8239087409443188
0.6179315557082391
===
hate
0.75
1.0
0.75
===
a
0.75
0.8239087409443188
0.6179315557082391
===
cat
1.0
1.0
1.0
===
The
0.75
0.8239087409443188
0.6179315557082391
===
dog
1.0
1.0
1.0
===
sat
0.75
0.8239087409443188
0.6179315557082391
===
on
0.75
0.8239087409443188
0.6179315557082391
===
my
0.75
0.8239087409443188
0.6179315557082391
===
bed
0.75
1.0
0.75
===
I
0.75
0.8239087409443188
0.6179315557082391
===
love
0.75
1.0
0.75
===
a
0.75
0.8239087409443188
0.6179315557082391
===
dog
1.0
1.0
1.0
===
====== document[0] ======
[('The', 0.6179315557082391), ('cat', 1.0), ('sat', 0.6179315557082391), ('on', 0.6179315557082391), ('my', 0.6179315557082391), ('face', 0.75), ('I', 0.6179315557082391), ('hate', 0.75), ('a', 0.6179315

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

In [62]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"
corpus = [d1, d2]
count_vect = CountVectorizer()
countv = count_vect.fit_transform(corpus)
print(countv.toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(count_vect.vocabulary_) # 각 단어의 인덱스가 어떻게 부여되었는지를 보여준다.

[[0 2 0 1 1 0 1 1 1 1]
 [1 0 2 0 0 1 1 1 1 1]]
{'the': 9, 'cat': 1, 'sat': 8, 'on': 7, 'my': 6, 'face': 3, 'hate': 4, 'dog': 2, 'bed': 0, 'love': 5}


In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"
corpus = [d1, d2]
tfidf_vect = TfidfVectorizer().fit(corpus)
tfidfv = tfidf_vect.transform(corpus)
print(tfidfv.toarray())
print(tfidf_vect.vocabulary_)


[[0.         0.70600557 0.         0.35300279 0.35300279 0.
  0.25116439 0.25116439 0.25116439 0.25116439]
 [0.35300279 0.         0.70600557 0.         0.         0.35300279
  0.25116439 0.25116439 0.25116439 0.25116439]]
{'the': 9, 'cat': 1, 'sat': 8, 'on': 7, 'my': 6, 'face': 3, 'hate': 4, 'dog': 2, 'bed': 0, 'love': 5}


#3.3 gensim 활용


In [65]:
import gensim.downloader as api
from gensim.models import TfidfModel
from gensim import corpora

In [67]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
doc_ls = [doc.split() for doc in corpus]
id2word = corpora.Dictionary(doc_ls)  # fit dictionary
corpus = [id2word.doc2bow(doc) for doc in doc_ls]  # convert corpus to BoW format


In [68]:
tfidf = TfidfModel(corpus)  # fit model
vector = tfidf[corpus[0]]  # apply model to the first corpus document
tfidf[corpus][0]


[(1, 0.49169813431045906),
 (2, 0.49169813431045906),
 (3, 0.49169813431045906),
 (4, 0.18147115159841573),
 (5, 0.49169813431045906)]

In [69]:
id2word.keys()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
TfidfModel?

#4 LSA(Latent Semantic Analysis)를 활용한 단어 벡터


4.1 sklearn 활용

In [72]:
doc_ls = ['바나나 사과 포도 포도',
         '사과 포도',
         '포도 바나나',
         '짜장면 짬뽕 탕수육',
         '볶음밥 탕수육',
         '짜장면 짬뽕',
         '라면 스시',
         '스시',
         '가츠동 스시 소바',
         '된장찌개 김치찌개 김치',
         '김치 된장',
         '비빔밥 김치'
         ]


In [74]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import TruncatedSVD
count_vect = CountVectorizer()
countv = count_vect.fit_transform(doc_ls)
svd = TruncatedSVD(n_components=2, algorithm='randomized', n_iter=100)
svd.fit(countv)


TruncatedSVD(algorithm='randomized', n_components=2, n_iter=100,
             random_state=None, tol=0.0)

In [75]:
features = count_vect.get_feature_names() # 단어 집합. 1,000개의 단어가 저장됨.
for i in range(len(features)) :
  print("{} : {}".format(features[i], svd.components_[:,i]))

가츠동 : [4.51503445e-18 2.33267499e-16]
김치 : [-3.96771268e-18  3.22973341e-15]
김치찌개 : [-3.88635790e-18  1.15908004e-15]
된장 : [-9.86536513e-18  9.84455471e-16]
된장찌개 : [8.48003007e-18 1.13752293e-15]
라면 : [-2.61995062e-17 -2.06248898e-16]
바나나 : [ 4.0824829e-01 -1.5008790e-16]
볶음밥 : [-5.99179462e-23  1.27737006e-01]
비빔밥 : [1.85588123e-17 1.03193900e-15]
사과 : [4.08248290e-01 1.60319925e-16]
소바 : [3.08762430e-17 1.87221458e-16]
스시 : [-4.4803874e-17 -3.4934820e-16]
짜장면 : [-2.87084057e-22  6.12024764e-01]
짬뽕 : [-2.87084057e-22  6.12024764e-01]
탕수육 : [-2.27166144e-22  4.84287758e-01]
포도 : [ 8.16496581e-01 -5.11581248e-18]


4.2 gensim 활용

In [76]:
doc_ls = ['바나나 사과 포도 포도',
         '사과 포도',
         '포도 바나나',
         '짜장면 짬뽕 탕수육',
         '볶음밥 탕수육',
         '짜장면 짬뽕',
         '라면 스시',
         '스시',
         '가츠동 스시 소바',
         '된장찌개 김치찌개 김치',
         '김치 된장',
         '비빔밥 김치'
         ]
doc_ls = [d.split() for d in doc_ls]


In [77]:
from gensim import corpora
from gensim.models import LsiModel
id2word = corpora.Dictionary(doc_ls) #사전 구축
corpus = [id2word.doc2bow(text) for text in doc_ls] # 코퍼스 생성
lsi = LsiModel(corpus, id2word=id2word, num_topics=2) #LSA 모델
for i in id2word.keys() :
  print("{} : {}".format(id2word[i], lsi.projection.u[i]))

바나나 : [ 4.08248290e-01 -5.65413233e-17]
사과 : [4.08248290e-01 4.95643345e-18]
포도 : [8.16496581e-01 1.14932130e-16]
짜장면 : [-2.07281276e-17  6.12024764e-01]
짬뽕 : [-2.13494626e-17  6.12024764e-01]
탕수육 : [7.45565596e-18 4.84287758e-01]
볶음밥 : [1.10562263e-17 1.27737006e-01]
라면 : [-3.16036264e-19  9.70436068e-16]
스시 : [-4.93677164e-19  3.37761995e-15]
가츠동 : [-1.87852177e-17  1.65241597e-15]
소바 : [6.96574451e-18 1.62019537e-15]
김치 : [-2.03647429e-17 -9.28558310e-16]
김치찌개 : [ 1.39398562e-17 -5.94456172e-16]
된장찌개 : [ 1.03428868e-17 -5.99052161e-16]
된장 : [-1.28388609e-17 -2.66775426e-16]
비빔밥 : [ 1.24228190e-17 -1.69685526e-16]
