<a href="https://colab.research.google.com/github/gyuholee94/NLP/blob/master/BOW%EA%B5%AC%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [49]:
import pandas as pd
import numpy as np
from collections import defaultdict
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
!pip install nltk 
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [51]:
d1 = docs[0]
d2 = docs[1]
d3 = docs[2]
d1_tokens = word_tokenize(d1)
print(d1_tokens)
d2_tokens = word_tokenize(d2)
print(d2_tokens)
d3_tokens = word_tokenize(d3)
print(d3_tokens)

['오늘', '동물원에서', '원숭이를', '봤어']
['오늘', '동물원에서', '코끼리를', '봤어', '봤어']
['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']


In [52]:
d_tokens = []
for x, y, z in zip(d1_tokens, d2_tokens, d3_tokens):
  d_tokens.append(x)
  d_tokens.append(y)
  d_tokens.append(z)



In [64]:
d_tokens_set = list(set(d_tokens))
print(d_tokens)
print(d_tokens_set)

['오늘', '오늘', '동물원에서', '동물원에서', '동물원에서', '원숭이에게', '원숭이를', '코끼리를', '바나나를', '봤어', '봤어', '줬어']
['줬어', '봤어', '원숭이를', '원숭이에게', '오늘', '코끼리를', '동물원에서', '바나나를']


In [75]:
values =array(d_tokens_set)
print(values)

label_enc = LabelEncoder()
d_tokens_index = label_enc.fit_transform(values)
print(d_tokens_index)#0으로 된 제로스에서 인덱스를 표현

['줬어' '봤어' '원숭이를' '원숭이에게' '오늘' '코끼리를' '동물원에서' '바나나를']
[6 2 4 5 3 7 0 1]


In [91]:
values = values.tolist()
d_tokens_index = d_tokens_index.tolist()

In [99]:
dic = {}
for i in range(len(values)):
  dic[values[i]] = d_tokens_index[i]

In [100]:
dic

{'동물원에서': 0,
 '바나나를': 1,
 '봤어': 2,
 '오늘': 3,
 '원숭이를': 4,
 '원숭이에게': 5,
 '줬어': 6,
 '코끼리를': 7}

In [141]:
one_hot_vectors = np.zeros((len(docs), len(dic)))
one_hot_vectors

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [143]:
for i, d in enumerate(dic):
  print(i, d)

0 줬어
1 봤어
2 원숭이를
3 원숭이에게
4 오늘
5 코끼리를
6 동물원에서
7 바나나를


In [135]:
for i in range(len(one_hot_vectors)):
  for j in range(len(dic)):
    if d1_tokens[j] == dic[]:
      one_hot_vectors[i][j] = one_hot_vectors[i][j]+1


0
0
0


In [128]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer()
print(vector.fit_transform(docs).toarray())

[[1 0 1 1 1 0 0 0]
 [1 0 2 1 0 0 0 1]
 [1 2 0 0 0 1 1 0]]


In [108]:
# for i, word in enumerate(docs):
#   index = dic.values
#   one_hot_vectors[i, int(index)]

TypeError: ignored

In [71]:
onehot_enc = OneHotEncoder(sparse=False)
d_tokens_index = d_tokens_index.reshape(len(d_tokens_index), 1) #n:1 matrix로 변환
print(d_tokens_index)#데이터 아낄 수 있음
d_tokens_enc = onehot_enc.fit_transform(np.array(d1).reshape(1, -1))
print(d_tokens_enc)

[[6]
 [2]
 [4]
 [5]
 [3]
 [7]
 [0]
 [1]]
[[1.]]


In [72]:
np.zeros(d_tokens_set, )

TypeError: ignored

In [ ]:
# def one_hot_encode(word_ls):
#   word2id_dic = defaultdict(lambda:len(word2id_dic))

#   for word in word_ls:
#     word2id_dic[word]
  
#   n_unique_words = len(word2id_dic)
#   one_hot_vectors = np.zeros((len(word_ls), n_unique_words))

#   for i, word in enumerate(word_ls):
#     index = word2id_dic[word]
#     one_hot_vectors[i, index] = 1
#   return one_hot_vectors

In [56]:
# one_hot_encode(d_tokens_set)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

['오늘 동물원에서 원숭이를 봤어' '오늘 동물원에서 코끼리를 봤어 봤어' '동물원에서 원숭이에게 바나나를 줬어 바나나를']
---------------
[1 2 0]
---------------
[[1]
 [2]
 [0]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
